// Restaurants

export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const CHANGE_RESTAURANT = 'CHANGE_RESTAURANT';

//Products

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

//Cart

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
